import turtle
tortuguita = turtle.Turtle()
fondo=turtle.Screen()
fondo.bgcolor("cyan")

#A
tortuguita.right(0)
tortuguita.pencolor("purple")
tortuguita.pensize(14)
tortuguita.shape("circle")
tortuguita.left(70)
tortuguita.forward(100)
tortuguita.right(130)
tortuguita.forward(60)
tortuguita.right(120)
tortuguita.forward(50)
tortuguita.right(180)
tortuguita.forward(50)
tortuguita.right(65)
tortuguita.forward(50)
a=tortuguita.pos()

#L
tortuguita.goto(a)
tortuguita.right(290)
tortuguita.pencolor("yellow")
tortuguita.pensize(14)
tortuguita.shape("circle")
tortuguita.left(90)
tortuguita.forward(100)
tortuguita.left(180)
tortuguita.forward(100)
b=tortuguita.pos()
#E
tortuguita.goto(b)
tortuguita.right(270)
tortuguita.pencolor("blue")
tortuguita.pensize(14)
tortuguita.shape("circle")
tortuguita.left(0)
tortuguita.forward(15)
tortuguita.left(90)
tortuguita.forward(100)
tortuguita.left(269)
tortuguita.forward(35)
tortuguita.right(180)
tortuguita.forward(35)
tortuguita.right(270)
tortuguita.forward(40)
tortuguita.right(269)
tortuguita.forward(35)
tortuguita.left(180)
tortuguita.forward(35)
tortuguita.right(270)
tortuguita.forward(61)
tortuguita.left(90)
tortuguita.forward(35)
c=tortuguita.pos()

#x
tortuguita.goto(c)
tortuguita.right(290)
tortuguita.pencolor("red")
tortuguita.pensize(14)
tortuguita.shape("circle")
tortuguita.left(355)
tortuguita.forward(110)
tortuguita.right(180)
tortuguita.forward(45)
tortuguita.right(140)
tortuguita.forward(45)
tortuguita.left(180)
tortuguita.forward(110)
d=tortuguita.pos()

#A
tortuguita.goto(d)
tortuguita.right(290)
tortuguita.pencolor("pink")
tortuguita.pensize(14)
tortuguita.shape("circle")
tortuguita.left(70)
tortuguita.forward(100)
tortuguita.right(130)
tortuguita.forward(60)
tortuguita.right(120)
tortuguita.forward(50)
tortuguita.right(180)
tortuguita.forward(50)
tortuguita.right(65)
tortuguita.forward(50)
e=tortuguita.pos()
#laberinto

medida = 8  
pen = turtle.Turtle()  
for i in range(medida * 2):
    pen.forward(i * 5) 
    pen.right(90)    
tortuguita.exitonclick()

